version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  bobby:
    steps:
      - checkout
      - run: echo "First Build"
  sally:
    steps:
      - checkout
      - run: echo "Second Build"
workflows:
  bobby_sally:
    jobs:
      - bobby
      - sally
