version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  bobby:
    steps:
      - checkout
      - run: echo "A first build"
  sally:
    steps:
      - checkout
      - run: echo "A second build"
